### ISSUE TITLE
"JOM - CPLEX interface. Failed to create LP" on Linux

### ISSUE THREAD

**Issue by mahdi7** [girtel/JOM#14]
While using Net2Plan application, creating a problem in CPLEX environment results in an error (returns a null pointer) on Linux machine, while it perfectly works on a Windows machine! 

Running
`Pointer lp = g.CPXcreateprob(env, status, "Problem name".getBytes());`
(line 90 of _SOLVERWRAPPER_CPLEX.java)
throws an exception, since the returned pointer is null. 

I am using CPLEX 12.8.0 (academic version) on both machines.

**Comment by ppavon** [comment]
Not enough information sorry, this may have to do with your CPLEX installation
